use_lars: False 
name: AdamW
warmup: False 
warmup_steps: 10000
warmup_times: ${.warmup_steps} 
warmup_epoch: 10
decay_step: 100000
decay_rate: .5
lr: 4e-4
weight_decay: 0. 
betas: [0.9, 0.999]
max_gnorm: 1.0 
lr_weight: 0.2
lr_bias: 0.0048
batch_size: ${running.batch_size}
epochs: ${running.epochs}
steps: []
gamma: 0.5
batch_sch: False # schedule lr per batch
optimizer: [AdamW, {lr: '${optimizer.lr}', betas: '${optimizer.betas}'}]
scheduler: [ExpDecayLR,{step_size: '${optimizer.decay_step}', gamma: '${optimizer.decay_rate}'}]
