name: PCFGLossHead
layers: []
scaling: False 
mini_1d_ll: false
mini_1d_2d: false 
kl_decay_ratio: 1.0
kl_cycle_steps: null # default to be cosine
kl_activation: "cosine"
kl_max_beta: 1e-2
kl_cycle: False
kl_max: null 
bh_beta: 0.0 # entropy regularizer
sh_beta: 0.0 # entropy regularizer
th_beta: 0.0 # entropy regularizer
