peep_rate: 1 
topk_best: -1
save_rate: 100 
skip_save: False 
save_last: False
nsampling: 1
infer_mode: False
batch_size: 32
epochs: 30 
save_epoch: False 
optim_rate: 1
v_peep_time: 10 # check the v generation
v_peep_topk: 5  # the first k in a batch
