name: DalleTokenEncHead
mode: gpt 
embed_dim: 1024 
txt_embed: Hard1DEmbedder
vis_embed: Hard1DEmbedder
txt_offset: 0
vis_offset: 0 
len_txt_seq: ${data.max_txt_len} 
len_vis_seq: ${..vq.max_vis_len} 
