# VQGAN Param.
name: PretrainedVQGAN
load: true # do we have to load model weights
gumbel: false
model_root: "" 
model_name: ""
model_file: ""
model_time: ""
vocab_size: 1024
embed_size: 256
max_vis_len: 256
